// type SidebarItemCategory = {
//   type: 'category';
//   label: string; // Sidebar label text.
//   items: SidebarItem[]; // Array of sidebar items.
//   className?: string;

//   // Category options:
//   collapsible: boolean; // Set the category to be collapsible
//   collapsed: boolean; // Set the category to be initially collapsed or open by default
//   link: SidebarItemCategoryLinkDoc | SidebarItemCategoryLinkGeneratedIndex;
// };

module.exports = {
  someSidebar: [
    {
      type: "category",
      label: "Introduction",
      collapsible: true,
      collapsed: false,
      items: [
        "introduction/what-is-modv",
        "introduction/security",
        "introduction/entities",
        "introduction/permissions",
      ],
    },
    {
      type: "category",
      label: "Mode d'emploi",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Connexion",
          items: [
            "user-guide/login-a",
            "user-guide/login-b",
            "user-guide/login-c",
            "user-guide/login-d",
            "user-guide/login-e",
          ],
        },
        "user-guide/logout",
        "user-guide/pass-reset",
        "user-guide/create-vault",
        "user-guide/subfolder",
        "user-guide/upload",
        "user-guide/version",
        "user-guide/delete",
        {
          type: "category",
          label: "Autorisations",
          items: [
            "user-guide/share-document",
            "user-guide/share-vault",
            "user-guide/share-folder",
          ],
        },

        "user-guide/other",
        {
          type: "category",
          label: "Signatures électroniques",
          items: [
            "user-guide/e-sig_setup",
            "user-guide/e-sig_signatories",
            "user-guide/e-sig_how_to_sign",
            "user-guide/e-sig_track",
            "user-guide/e-sig_download",
          ],
        },
        {
          type: "category",
          label: "Favoris",
          items: ["user-guide/fav_toggle", "user-guide/fav_drag"],
        },
        "user-guide/ocring",

        "user-guide/tags",
        "user-guide/search",
      ],
    },
  ],
};
// module.exports = {
//   someSidebar: {
//     Introduction: [
//       "introduction/what-is-modv",
//       "introduction/security",
//       "introduction/entities",
//       "introduction/permissions",
//     ],
//     // "User Guide": [
//     //   "user-guide/login-a",
//     //   "user-guide/login-b",
//     //   "user-guide/login-c",
//     //   "user-guide/login-d",
//     //   "user-guide/login-e",
//     //   "user-guide/create-vault",
// "user-guide/upload",
// "user-guide/subfolder",
// "user-guide/permissions",
// "user-guide/permissions-v",
// "user-guide/delete",
// "user-guide/other",
//     //   "user-guide/e-signature",
//     // ],
//     // Apis: ["apis/authentication", "apis/vaults", "apis/folders"],
//   },
// };

// /**
//  * Creating a sidebar enables you to:
//  - create an ordered group of docs
//  - render a sidebar for each doc of that group
//  - provide next/previous navigation

//  The sidebars can be generated from the filesystem, or explicitly defined here.

//  Create as many sidebars as you want.
//  */

// // @ts-check

// /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['hello'],
//     },
//   ],
//    */
// };

// module.exports = sidebars;
